import type { SupabaseClient } from "@supabase/supabase-js";
import { createClient } from "../../db/server";

/**
 * How long an identical (operation, input_hash) success is considered fresh enough to
 * skip a re-run for. This guards against accidental duplicate billing -- a double-click,
 * a resubmitted form after a slow response, a retried request -- not a long-lived cache;
 * the operation-specific freshness checks that already exist (e.g. understandProduct's
 * product_profile_generated_at comparison) are the real caching layer and are keyed off
 * domain data, not this window.
 */
export const DEDUP_WINDOW_MS = 5 * 60 * 1000;

/**
 * True if a succeeded ai_runs row with this exact (workspace, operation, input_hash,
 * model) exists within the dedup window. Callers should skip the paid model call and
 * re-read their own persisted result instead -- the earlier call already wrote it.
 *
 * `model` is optional only for backward compatibility with callers that haven't been
 * migrated to pass it; always pass it for BYOK operations (docs/byok-ai-requirements.md
 * §13's cache identity is input_hash + operation + prompt_version + model) -- without it,
 * a workspace that switches AI provider between two identical-input calls could
 * incorrectly reuse a result generated by the previous provider's model.
 */
export async function hasRecentSuccess(
  workspaceId: string,
  operation: string,
  inputHash: string,
  client?: SupabaseClient,
  model?: string,
): Promise<boolean> {
  const supabase = client ?? (await createClient());
  const since = new Date(Date.now() - DEDUP_WINDOW_MS).toISOString();
  let query = supabase
    .from("ai_runs")
    .select("id")
    .eq("workspace_id", workspaceId)
    .eq("operation", operation)
    .eq("input_hash", inputHash)
    .eq("status", "succeeded")
    .gte("created_at", since);
  if (model) query = query.eq("model", model);
  const { data, error } = await query.limit(1).maybeSingle();
  if (error) throw error;
  return data !== null;
}
