import type { Contact } from "../contacts/types";
import type { BuyerPersona } from "../personas/types";
import type { EvidenceItem } from "../research/types";

/** DISC-OFFER-P0-06.3: "Buyer/Person Intelligence" -- a per-contact enrichment layer
 * over 06.2's own `BuyingCommitteeMatch` (contact + matched persona), adding the
 * remaining fields the doc's own field list asks for: seniority, relevance to offering,
 * contactability, supporting evidence, and a confidence in this specific
 * characterization. The doc's own "Do not invent people or roles" holds structurally
 * throughout this module: every `BuyerPersonIntelligence` wraps one real
 * `discovery.contacts` row, and every derived field below is either read straight off
 * that row or computed by a pure, deterministic rule (see seniority.ts/contactability.ts/
 * relevance.ts/supporting-evidence.ts) -- never generated by an AI call. */

export type Seniority = "c_level" | "vp" | "director" | "manager" | "individual_contributor" | "unknown";

export const SENIORITY_LABEL: Record<Seniority, string> = {
  c_level: "C-level",
  vp: "VP",
  director: "Director",
  manager: "Manager",
  individual_contributor: "Individual contributor",
  unknown: "Unknown",
};

/** "unknown" is deliberately distinct from "low" -- a contact with no job title on file
 * has unassessable relevance, which is not the same claim as "assessed and found
 * irrelevant" (the same "absence of evidence isn't evidence of absence" precision
 * 05.2/05.5 already established for missing score components/insufficient_evidence). */
export type RelevanceToOffering = "high" | "medium" | "low" | "unknown";

export const RELEVANCE_LABEL: Record<RelevanceToOffering, string> = {
  high: "High",
  medium: "Medium",
  low: "Low",
  unknown: "Unknown",
};

export type Contactability = "high" | "medium" | "low";

export const CONTACTABILITY_LABEL: Record<Contactability, string> = {
  high: "High",
  medium: "Medium",
  low: "Low",
};

export type BuyerIntelligenceConfidence = "low" | "medium" | "high";

export type BuyerPersonIntelligence = {
  contact: Contact;
  /** Display name, falling back to a plain placeholder rather than hiding a contact
   * with no name recorded -- a real person the founder added is never dropped from the
   * list for lacking a field. */
  name: string;
  title: string | null;
  seniority: Seniority;
  /** "Likely role in buying committee" (doc's own field) -- the same real, matched
   * `discovery.buyer_personas` row 06.2's `matchBuyingCommittee` already produces, null
   * when no persona's title matches this contact's own job title. */
  persona: BuyerPersona | null;
  relevance: RelevanceToOffering;
  relevanceReason: string;
  contactability: Contactability;
  contactabilityReason: string;
  supportingEvidence: EvidenceItem[];
  confidence: BuyerIntelligenceConfidence;
};
