import { createAdminClient } from "../db/admin";
import { createClient } from "../db/server";
import { isSuperadmin } from "../rbac/platform-admin";
import { renderExport } from "./render";
import { contentDisposition, parseFormat, parseScope } from "./server";
import type { ExportFormat, ExportScope, ExportWorkbookDefinition } from "./types";

/**
 * EXP-ADMIN-01..07 on EXP-PLAT-05's rails -- the platform-administration counterpart of
 * runBusinessExport(). A platform export belongs to no business, so the checks are
 * different: a signed-in superadmin (the same isSuperadmin() every /platform page uses),
 * and the audit entry goes to platform.audit_log as `exported` through the service-role-
 * only platform.write_export_audit_log() (20260926110000). Adapters must never put a
 * secret, credential, key, token or encryption material in a sheet (§18); each one reads
 * through the same superadmin-scoped queries its page does.
 */

export type PlatformExportContext = {
  userId: string;
  userEmail: string | null;
  timeZone: string;
  format: ExportFormat;
  scope: ExportScope;
};

export type PlatformExportAdapter<F = Record<string, string>> = {
  /** `platform.<resource>`, e.g. `platform.audit`. */
  id: string;
  parseFilters?: (params: URLSearchParams) => F;
  describeFilters?: (filters: F) => Record<string, string>;
  load: (context: PlatformExportContext, filters: F) => Promise<ExportWorkbookDefinition>;
};

const PLATFORM_TIME_ZONE = "Asia/Kolkata";

const json = (status: number, body: Record<string, unknown>) =>
  new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json", "cache-control": "no-store" } });

export async function runPlatformExport<F>(request: Request, adapter: PlatformExportAdapter<F>): Promise<Response> {
  const url = new URL(request.url);
  const format = parseFormat(url.searchParams.get("format"));
  if (!format) return json(400, { error: "bad_request", message: "Choose CSV or Excel." });
  const scope = parseScope(url.searchParams.get("scope"));

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return json(401, { error: "unauthenticated", message: "Sign in to export." });
  // Not found rather than forbidden, like every other /platform surface: a non-admin
  // shouldn't learn which platform exports exist.
  if (!(await isSuperadmin())) return json(404, { error: "not_found", message: "Unknown export." });

  const context: PlatformExportContext = { userId: user.id, userEmail: user.email ?? null, timeZone: PLATFORM_TIME_ZONE, format, scope };
  const filters = adapter.parseFilters ? adapter.parseFilters(url.searchParams) : (Object.fromEntries(url.searchParams) as unknown as F);
  const labels = adapter.describeFilters ? adapter.describeFilters(filters) : {};
  const resource = adapter.id.split(".")[1] ?? adapter.id;
  const audit = (outcome: "generated" | "failed", rowCount?: number) =>
    createAdminClient({ schema: "platform" }).rpc("write_export_audit_log", {
      p_actor_id: user.id,
      p_resource_type: `export.${resource}`,
      p_new_value: { format, scope, outcome, filters: labels, ...(rowCount != null ? { row_count: rowCount } : {}) },
    });

  try {
    const workbook: ExportWorkbookDefinition = await adapter.load(context, filters);
    const file = await renderExport(workbook, format, {
      timeZone: context.timeZone,
      generatedAt: new Date(),
      info: {
        Scope: "Platform administration",
        "Generated by": context.userEmail ?? context.userId,
        ...(Object.keys(labels).length > 0 ? { Filters: Object.entries(labels).map(([k, v]) => `${k}: ${v}`).join("; ") } : {}),
      },
    });
    const { error } = await audit("generated", file.rowCount);
    if (error) throw error;
    return new Response(file.body as BodyInit, {
      status: 200,
      headers: {
        "content-type": file.contentType,
        "content-disposition": contentDisposition(file.filename),
        "cache-control": "no-store",
        "x-content-type-options": "nosniff",
        "x-export-row-count": String(file.rowCount),
      },
    });
  } catch (error) {
    console.error(`[exports] ${adapter.id} failed`, error);
    await audit("failed").then(undefined, () => undefined);
    return json(500, { error: "export_failed", message: "We could not generate this export. No data was changed." });
  }
}
