/**
 * EXP-PLAT-01 -- the one export contract every module's adapter speaks
 * (docs/plan/13-DATA-EXPORT-BACKLOG.md §9).
 *
 * Framework-neutral on purpose: nothing here imports React or Next, so the same
 * definitions drive the CSV writer (./csv.ts), the Excel writer (./xlsx.ts), the export
 * route (./server.ts) and unit tests alike. An adapter describes *what* a dataset is --
 * its sheets, columns and rows -- and never *how* a file is written.
 */

export type ExportFormat = "csv" | "xlsx";

/**
 * "view" is exactly what the page is showing: its filters and, for a paginated list, the
 * current page. "all" is the same filters with no pagination limit -- never "everything in
 * the tenant" while a filter is active (§7).
 */
export type ExportScope = "view" | "all";

/**
 * How a column's value is written. `text` is the default. Numbers stay numbers in both
 * formats; `currency` and `percent` differ only in Excel's number format (a percent is
 * a fraction: 0.25 means 25%, in CSV and Excel alike, §42).
 */
export type ExportColumnType =
  | "text"
  | "number"
  | "integer"
  | "currency"
  | "percent"
  | "date"
  | "datetime"
  | "boolean";

export type ExportColumn<T> = {
  /** Stable machine key -- used for tests and to pick columns, never shown to a person. */
  key: string;
  /** The header a person reads, in both formats. */
  header: string;
  getValue: (row: T) => unknown;
  type?: ExportColumnType;
  /** Excel column width in characters; derived from the content when omitted. */
  width?: number;
  /** For `currency`: the ISO code when every row shares one, so Excel can show the
   * symbol. Leave unset when a sheet can mix currencies -- carry a separate currency
   * column instead (§41). */
  currency?: string;
};

export type ExportSheet<T = unknown> = {
  /** Worksheet name. Trimmed to Excel's 31 characters and made unique by the writer. */
  sheetName: string;
  columns: ExportColumn<T>[];
  rows: T[];
};

export type ExportWorkbookDefinition = {
  /** `wonderark_<module>_<resource>` -- the writer adds the date and extension
   * (see ./filename.ts). */
  module: string;
  resource: string;
  /** Human title for audit entries, notifications and the Excel "Export info" sheet --
   * "CRM leads", "Profit & Loss". */
  title: string;
  /** One sheet per logically independent dataset (§33). CSV writes one of them --
   * `csvSheet` when given, otherwise the first. */
  sheets: ExportSheet<any>[]; // eslint-disable-line @typescript-eslint/no-explicit-any -- each sheet has its own row type
  csvSheet?: string;
  /** Report parameters worth keeping with the file (period, filters) -- written to the
   * Excel "Export info" sheet, never into a CSV, which stays strictly tabular (§14). */
  metadata?: Record<string, string>;
};

/** What a writer produced, ready to stream to the browser. */
export type ExportFile = {
  filename: string;
  contentType: string;
  body: Uint8Array;
  rowCount: number;
};

/** The facts a writer needs that are not part of the dataset itself. */
export type ExportRenderOptions = {
  /** IANA zone the business works in -- datetimes are written in this zone so a local
   * date never shifts to another calendar day (§40). */
  timeZone: string;
  /** When the export was generated -- names the file and fills "Generated at". */
  generatedAt: Date;
  /** Extra rows for the Excel "Export info" sheet: Business, Generated by, Scope... */
  info?: Record<string, string>;
};

export const EXPORT_CONTENT_TYPE: Record<ExportFormat, string> = {
  csv: "text/csv; charset=utf-8",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
};

/** Rows a request may produce synchronously before the export is handed to a background
 * job instead (§17, EXP-PLAT-06). */
export const SYNC_EXPORT_ROW_LIMIT = 25_000;
