import type { PurchaseMatchStatus, SupplierReconciliationRow } from "./types";

/**
 * COMPLY-P0-08.3 (Match Explanation): "explain WHY a supplier's own reconciliation
 * status is what it is" -- deterministic, not an LLM call (CLAUDE.md principle 4, "do
 * not use an LLM for deterministic operations"; backlog rule 12, "distinguish
 * regulatory fact, software rule, calculated result, and AI explanation" -- these are
 * software-rule candidate causes, never presented as a confirmed diagnosis, and never
 * generated by a model). Every possible-cause string below is grounded in REAL GST
 * reconciliation practice researched via `WebSearch` this story (busy.in's "GSTR-2B and
 * Rule 37A" explainer, precisa.in's "Reconcile ITC Mismatches Between GSTR-2B and
 * GSTR-3B," and caclubindia.com's own "GSTR-2B Mismatch and ITC Protection" guide, all
 * cross-referencing the same small set of real-world causes) -- never invented from
 * memory, and stated as POSSIBILITIES a human should check, never as a claim about what
 * actually happened (backlog rule 11: never claim "compliant"/diagnosed just because a
 * computation ran).
 */

const MISSING_IN_2B_CAUSES: string[] = [
  "Your supplier may not have filed their GSTR-1/IFF for this period yet -- GSTR-2B only includes invoices from suppliers who filed by the cut-off date.",
  "Your supplier may have filed after the cut-off date for this GSTR-2B statement -- it would then appear in a LATER month's 2B instead.",
  "Your supplier may have entered your GSTIN incorrectly, or reported this invoice against the wrong tax period.",
  "This purchase may genuinely be from an unregistered supplier or under reverse charge, in which case it is expected not to appear in any GSTR-2B.",
];

const MISSING_IN_BOOKS_CAUSES: string[] = [
  "This purchase may not yet be recorded in your own books for this period -- check for an invoice received but not yet entered.",
  "Your supplier may have duplicated this invoice, or reported it under a period different from when you actually received the goods/services.",
  "This may belong to a different business location/GSTIN of yours if you operate under more than one registration.",
];

const MISMATCH_CAUSES: string[] = [
  "A rounding difference between your books and your supplier's own reported figures.",
  "Your supplier may have amended this invoice after originally filing it.",
  "Partial reporting -- your supplier may have split, or only partially reported, this period's invoices.",
  "An incorrect tax rate or place of supply applied by either side.",
];

export function possibleCausesFor(status: PurchaseMatchStatus): string[] {
  switch (status) {
    case "missing_in_2b":
      return MISSING_IN_2B_CAUSES;
    case "missing_in_books":
      return MISSING_IN_BOOKS_CAUSES;
    case "mismatched":
      return MISMATCH_CAUSES;
    case "matched":
      return [];
  }
}

export type SupplierMatchExplanation = {
  row: SupplierReconciliationRow;
  possibleCauses: string[];
};

/** Pure: attaches the deterministic candidate-cause list for a row's own status. A
 * `"matched"` row gets an empty list -- there is nothing to explain. */
export function explainSupplierMatch(row: SupplierReconciliationRow): SupplierMatchExplanation {
  return { row, possibleCauses: possibleCausesFor(row.status) };
}
