import { createAdminClient } from "../db/admin";
import { SITE_URL } from "../site";
import { BRAND_NAME } from "../lib/brand";
import { requireBillingManager, type BillingManager } from "./access";
import { getPlan, isFreePlan, listActivePlanPrices, type CatalogPlan, type PlanPrice } from "./catalog";
import { auditBilling, logBilling } from "./observability";
import { createProvider, isCheckoutReady, loadProviderConfigs } from "./provider-config";
import { reconcileSubscriptionLicenses } from "./provisioning";
import { businessHadTrial, isSupportedCurrency, isTrialEligible, loadLifecycleSettings, type SubscriptionLifecycleSettings } from "./lifecycle";
import {
  BillingNotConfiguredError,
  BillingProviderError,
  type BillingInterval,
  type CheckoutResult,
  type ProviderConfig,
} from "./subscription-types";

/**
 * BILL-08 -- starting a checkout (§26, §27, §50-§53).
 *
 * The browser names a plan, an interval and an idempotency key -- nothing else. Amount,
 * currency, provider, provider price and the modules the plan licenses are all resolved
 * here from WonderArk's own catalogue; the request cannot carry them. The caller must be
 * an owner or admin of the business's account.
 *
 * Idempotency is two-layered (§53): the (business_id, idempotency_key) unique index makes
 * two tabs share one checkout session, and the session's id is the provider idempotency
 * key, so even a retried provider call creates one provider checkout.
 *
 * Nothing here grants anything for a paid plan: a subscription and its licences exist only
 * once a verified webhook says the provider has taken payment (§3.1, BILL-12/13). The free
 * plan is the one exception, activated internally with no provider at all (§12).
 */

export class CheckoutError extends Error {
  constructor(
    readonly code:
      | "invalid_plan"
      | "already_subscribed"
      | "already_on_plan"
      | "unsupported_currency"
      | "not_configured"
      | "session_expired"
      | "rate_limited"
      | "provider_error",
    message: string,
  ) {
    super(message);
    this.name = "CheckoutError";
  }
}

export type StartCheckoutInput = {
  businessId: string;
  businessSlug: string;
  planId: string;
  billingInterval: BillingInterval;
  /** Generated by the page once per plan choice; a UUID. */
  idempotencyKey: string;
};

type LiveSubscription = { id: string; plan_id: string; provider: string; status: string };

type SessionRow = {
  id: string;
  plan_id: string;
  provider: string;
  status: string;
  expires_at: string;
  provider_subscription_id: string | null;
  checkout_url: string | null;
};

const platformAdmin = () => createAdminClient({ schema: "platform" });

const CHECKOUT_WINDOW_MS = 10 * 60 * 1000;
const MAX_CHECKOUTS_PER_WINDOW = 10;

async function liveSubscription(businessId: string): Promise<LiveSubscription | null> {
  const { data, error } = await platformAdmin()
    .from("subscriptions")
    .select("id, plan_id, provider, status")
    .eq("business_id", businessId)
    .in("status", ["trialing", "active", "past_due", "paused", "cancel_scheduled", "unpaid"])
    .maybeSingle();
  if (error) throw error;
  return data as LiveSubscription | null;
}

async function businessCurrency(businessId: string, fallback: string): Promise<string> {
  const core = createAdminClient({ schema: "core" });
  const { data, error } = await core.from("business_settings").select("currency").eq("business_id", businessId).maybeSingle();
  if (error) throw error;
  return ((data?.currency as string | null) ?? fallback).toUpperCase();
}

/**
 * BILL-06 + BILL-07 together: the first provider, in priority order, that is ready, takes
 * the business's currency, and has an active price for this plan and interval in its
 * current environment. Pure, for tests.
 */
export function choosePriceForCheckout(
  configs: ProviderConfig[],
  prices: PlanPrice[],
  { planId, currency, interval }: { planId: string; currency: string; interval: BillingInterval },
): { config: ProviderConfig; price: PlanPrice } | { error: "unsupported_currency" | "not_configured" } {
  const ready = configs.filter(isCheckoutReady).sort((a, b) => a.priority - b.priority);
  const takingCurrency = ready.filter((c) => c.supportedCurrencies.includes(currency));
  if (takingCurrency.length === 0) return { error: ready.length === 0 ? "not_configured" : "unsupported_currency" };
  for (const config of takingCurrency) {
    const price = prices.find(
      (p) =>
        p.active &&
        p.planId === planId &&
        p.provider === config.provider &&
        p.environment === config.environment &&
        p.currency === currency &&
        p.billingInterval === interval,
    );
    if (price) return { config, price };
  }
  return { error: "unsupported_currency" };
}

export async function startCheckout(input: StartCheckoutInput): Promise<CheckoutResult> {
  const started = Date.now();
  const manager = await requireBillingManager(input.businessId);
  const plan = await getPlan(input.planId);
  if (!plan || plan.status !== "active") throw new CheckoutError("invalid_plan", "That plan isn't available.");

  const current = await liveSubscription(manager.businessId);
  // An internal trial of this plan may be converted to the paid plan early
  // (PLATFORM-P1-04.2); any other subscription to the same plan is a no-op.
  const onTrial = current?.provider === "internal" && current.status === "trialing";
  if (current && current.plan_id === plan.id && !onTrial) throw new CheckoutError("already_on_plan", "You're already on this plan.");
  // One paid subscription per business (§50); plan changes go through Change plan.
  if (current && current.provider !== "internal") {
    throw new CheckoutError("already_subscribed", "You already have an active subscription. Manage your current plan to change it.");
  }

  if (isFreePlan(plan)) return activateFreePlan(manager, plan, input.idempotencyKey);

  const lifecycle = await loadLifecycleSettings();
  // PLATFORM-P1-04.2: an eligible plan starts with the configured free trial -- no
  // provider, no payment details -- once per business.
  if (!onTrial && isTrialEligible(lifecycle, plan.id, await businessHadTrial(manager.businessId))) {
    return activateTrial(manager, plan, lifecycle, input.idempotencyKey);
  }

  const currency = await businessCurrency(manager.businessId, plan.currency);
  // PLATFORM-P1-05.1: WonderArk bills only in the platform's supported currencies.
  if (!isSupportedCurrency(lifecycle, currency)) {
    logBilling("billing.checkout", { business_id: manager.businessId, operation: "start", status: "failed", error_code: "unsupported_currency" });
    throw new CheckoutError("unsupported_currency", "This plan is not available in your billing currency.");
  }
  const [configs, prices] = await Promise.all([loadProviderConfigs(), listActivePlanPrices({ planId: plan.id })]);
  const choice = choosePriceForCheckout(configs, prices, { planId: plan.id, currency, interval: input.billingInterval });
  if ("error" in choice) {
    logBilling("billing.checkout", { business_id: manager.businessId, operation: "start", status: "failed", error_code: choice.error });
    if (choice.error === "not_configured") throw new BillingNotConfiguredError("Online payments aren't set up yet. Please contact support to change your plan.");
    throw new CheckoutError("unsupported_currency", "This plan is not available in your billing currency.");
  }
  const { config, price } = choice;

  // §101 rate limit: provider checkouts a business can start in ten minutes. Retries with
  // the same idempotency key reuse their session and don't count.
  const idempotencyKey = `${plan.id}:${input.billingInterval}:${input.idempotencyKey}`;
  const { count: recent, error: recentError } = await platformAdmin()
    .from("checkout_sessions")
    .select("id", { count: "exact", head: true })
    .eq("business_id", manager.businessId)
    .neq("idempotency_key", idempotencyKey)
    .gte("created_at", new Date(Date.now() - CHECKOUT_WINDOW_MS).toISOString());
  if (recentError) throw recentError;
  if ((recent ?? 0) >= MAX_CHECKOUTS_PER_WINDOW) {
    throw new CheckoutError("rate_limited", "Too many checkout attempts. Please wait a few minutes and try again.");
  }
  const session = await openSession(manager, plan.id, price, config, idempotencyKey);
  if (session.status !== "open") {
    throw new CheckoutError("session_expired", "Session expired. Please start checkout again.");
  }
  if (new Date(session.expires_at) <= new Date()) {
    await platformAdmin().from("checkout_sessions").update({ status: "expired" }).eq("id", session.id).eq("status", "open");
    throw new CheckoutError("session_expired", "Session expired. Please start checkout again.");
  }

  // Same tab clicked twice: hand back the checkout already created.
  if (session.provider_subscription_id || session.checkout_url) {
    return toResult(config, session.id, session.provider_subscription_id, session.checkout_url, manager, plan);
  }

  const provider = createProvider(config);
  try {
    const customerId = await ensureBillingCustomer(manager, config, provider, currency);
    const returnBase = `${SITE_URL}/${encodeURIComponent(input.businessSlug)}/billing`;
    const checkout = await provider.createCheckout({
      customerId,
      providerPriceId: price.providerPriceId,
      sessionId: session.id,
      businessId: manager.businessId,
      planKey: plan.key,
      billingInterval: input.billingInterval,
      customerEmail: manager.email,
      successUrl: `${returnBase}/success?session=${session.id}`,
      cancelUrl: `${returnBase}/failed?session=${session.id}&reason=cancelled`,
      idempotencyKey: session.id,
    });
    const { error } = await platformAdmin()
      .from("checkout_sessions")
      .update({
        provider_checkout_id: checkout.checkoutId,
        provider_subscription_id: checkout.subscriptionId,
        checkout_url: checkout.redirectUrl,
      })
      .eq("id", session.id);
    if (error) throw error;

    await auditBilling(
      manager.businessId,
      "billing.checkout_started",
      "checkout_session",
      session.id,
      { plan: plan.key, provider: config.provider, environment: config.environment, currency, interval: input.billingInterval, amount: price.amount },
      manager.userId,
    );
    logBilling("billing.checkout", { business_id: manager.businessId, provider: config.provider, operation: "start", status: "started", duration_ms: Date.now() - started });
    return toResult(config, session.id, checkout.subscriptionId, checkout.redirectUrl, manager, plan);
  } catch (error) {
    const code = error instanceof BillingProviderError ? error.code : "internal";
    await platformAdmin()
      .from("checkout_sessions")
      .update({ status: "failed", failure_message_safe: "We couldn't start checkout. Please try again." })
      .eq("id", session.id);
    await auditBilling(manager.businessId, "billing.checkout_failed", "checkout_session", session.id, { provider: config.provider, error_code: code }, manager.userId);
    logBilling("billing.checkout", { business_id: manager.businessId, provider: config.provider, operation: "start", status: "failed", error_code: code });
    throw new CheckoutError("provider_error", "We couldn't start checkout. Please try again.");
  }
}

function toResult(
  config: ProviderConfig,
  sessionId: string,
  providerSubscriptionId: string | null,
  url: string | null,
  manager: BillingManager,
  plan: CatalogPlan,
): CheckoutResult {
  if (config.provider === "stripe") {
    if (!url) throw new CheckoutError("provider_error", "We couldn't start checkout. Please try again.");
    return { provider: "stripe", mode: "redirect", url, sessionId };
  }
  if (!providerSubscriptionId || !config.publicKey) throw new CheckoutError("provider_error", "We couldn't start checkout. Please try again.");
  // Exactly what Razorpay's Checkout.js needs: the public Key ID and the subscription id.
  // The Key Secret never leaves the server (§27, §65).
  return {
    provider: "razorpay",
    mode: "checkout",
    sessionId,
    checkoutOptions: {
      key: config.publicKey,
      subscription_id: providerSubscriptionId,
      name: BRAND_NAME,
      description: `${plan.name} plan for ${manager.businessName}`.slice(0, 250),
      prefill: manager.email ? { email: manager.email } : {},
      notes: { business_id: manager.businessId, checkout_session_id: sessionId },
    },
  };
}

async function openSession(
  manager: BillingManager,
  planId: string,
  price: PlanPrice,
  config: ProviderConfig,
  idempotencyKey: string,
): Promise<SessionRow> {
  const columns = "id, plan_id, provider, status, expires_at, provider_subscription_id, checkout_url";
  const platform = platformAdmin();
  const { data, error } = await platform
    .from("checkout_sessions")
    .insert({
      business_id: manager.businessId,
      plan_id: planId,
      plan_price_id: price.id,
      provider: config.provider,
      environment: config.environment,
      idempotency_key: idempotencyKey,
      requested_by: manager.userId,
    })
    .select(columns)
    .single();
  if (!error) return data as SessionRow;
  if (error.code !== "23505") throw error;
  const { data: existing, error: readError } = await platform
    .from("checkout_sessions")
    .select(columns)
    .eq("business_id", manager.businessId)
    .eq("idempotency_key", idempotencyKey)
    .single();
  if (readError) throw readError;
  return existing as SessionRow;
}

async function ensureBillingCustomer(
  manager: BillingManager,
  config: ProviderConfig,
  provider: ReturnType<typeof createProvider>,
  currency: string,
): Promise<string> {
  const platform = platformAdmin();
  const { data: existing, error } = await platform
    .from("billing_customers")
    .select("provider_customer_id")
    .eq("business_id", manager.businessId)
    .eq("provider", config.provider)
    .eq("environment", config.environment)
    .maybeSingle();
  if (error) throw error;
  if (existing) return existing.provider_customer_id as string;

  const customer = await provider.createCustomer({ businessId: manager.businessId, name: manager.businessName, email: manager.email });
  const { error: insertError } = await platform.from("billing_customers").insert({
    business_id: manager.businessId,
    provider: config.provider,
    environment: config.environment,
    provider_customer_id: customer.id,
    email: manager.email,
    currency,
  });
  if (insertError && insertError.code !== "23505") throw insertError;
  return customer.id;
}

/** §12 -- the free plan: an internal subscription, no provider, licences at once. */
async function activateFreePlan(manager: BillingManager, plan: CatalogPlan, idempotencyKey: string): Promise<CheckoutResult> {
  const platform = platformAdmin();
  const now = new Date().toISOString();
  const { data: sub, error } = await platform
    .from("subscriptions")
    .insert({
      business_id: manager.businessId,
      plan_id: plan.id,
      provider: "internal",
      environment: "live",
      status: "active",
      provider_status: "active",
      currency: plan.currency,
      amount: 0,
      current_period_start: now,
    })
    .select("id")
    .single();
  if (error) {
    if (error.code === "23505") throw new CheckoutError("already_subscribed", "You already have an active subscription. Manage your current plan to change it.");
    throw error;
  }
  const { data: session, error: sessionError } = await platform
    .from("checkout_sessions")
    .insert({
      business_id: manager.businessId,
      plan_id: plan.id,
      provider: "internal",
      environment: "live",
      idempotency_key: `${plan.id}:free:${idempotencyKey}`,
      requested_by: manager.userId,
      subscription_id: sub.id,
      status: "completed",
      completed_at: now,
    })
    .select("id")
    .single();
  if (sessionError) throw sessionError;

  await auditBilling(manager.businessId, "billing.subscription_created", "subscription", sub.id as string, { provider: "internal", plan: plan.key }, manager.userId);
  await reconcileSubscriptionLicenses(sub.id as string);
  logBilling("billing.checkout", { business_id: manager.businessId, subscription_id: sub.id as string, provider: "internal", operation: "start", status: "activated" });
  return { provider: "internal", mode: "activated", sessionId: session.id as string };
}

/**
 * PLATFORM-P1-04.2 -- a free trial: an internal subscription in `trialing`, no provider,
 * ending after the configured number of days. Licences follow the trial entitlements
 * (reconcileSubscriptionLicenses); when the trial ends without a paid checkout,
 * expireEndedTrials() ends it and those licences go into the read-only grace like any
 * other ended subscription -- nothing is deleted (04.4). Converting early is a normal
 * paid checkout of the same plan, which replaces the internal subscription (sync.ts).
 */
async function activateTrial(manager: BillingManager, plan: CatalogPlan, lifecycle: SubscriptionLifecycleSettings, idempotencyKey: string): Promise<CheckoutResult> {
  const platform = platformAdmin();
  const now = new Date();
  const trialEnd = new Date(now.getTime() + lifecycle.trialDays * 24 * 60 * 60 * 1000).toISOString();
  // A trial replaces the free plan's internal subscription (one live subscription each).
  const { error: freeError } = await platform
    .from("subscriptions")
    .update({ status: "cancelled", cancelled_at: now.toISOString(), updated_at: now.toISOString() })
    .eq("business_id", manager.businessId)
    .eq("provider", "internal")
    .eq("status", "active");
  if (freeError) throw freeError;
  const { data: sub, error } = await platform
    .from("subscriptions")
    .insert({
      business_id: manager.businessId,
      plan_id: plan.id,
      provider: "internal",
      environment: "live",
      status: "trialing",
      provider_status: "trialing",
      currency: plan.currency,
      amount: 0,
      trial_start: now.toISOString(),
      trial_end: trialEnd,
      current_period_start: now.toISOString(),
      current_period_end: trialEnd,
      metadata: { trial: true, trial_days: lifecycle.trialDays },
    })
    .select("id")
    .single();
  if (error) {
    if (error.code === "23505") throw new CheckoutError("already_subscribed", "You already have an active subscription. Manage your current plan to change it.");
    throw error;
  }
  const { data: session, error: sessionError } = await platform
    .from("checkout_sessions")
    .insert({
      business_id: manager.businessId,
      plan_id: plan.id,
      provider: "internal",
      environment: "live",
      idempotency_key: `${plan.id}:trial:${idempotencyKey}`,
      requested_by: manager.userId,
      subscription_id: sub.id,
      status: "completed",
      completed_at: now.toISOString(),
    })
    .select("id")
    .single();
  if (sessionError) throw sessionError;

  await auditBilling(manager.businessId, "billing.trial_started", "subscription", sub.id as string, { plan: plan.key, trial_days: lifecycle.trialDays, trial_end: trialEnd }, manager.userId);
  await reconcileSubscriptionLicenses(sub.id as string);
  logBilling("billing.checkout", { business_id: manager.businessId, subscription_id: sub.id as string, provider: "internal", operation: "trial", status: "activated" });
  return { provider: "internal", mode: "activated", sessionId: session.id as string };
}

/** PLATFORM-P1-04.2 -- ends every internal trial whose time is up. Its licences move into
 * the read-only grace (never deleted) and the business falls back to the free plan. */
export async function expireEndedTrials(): Promise<number> {
  const { data, error } = await platformAdmin()
    .from("subscriptions")
    .update({ status: "expired", updated_at: new Date().toISOString() })
    .eq("provider", "internal")
    .eq("status", "trialing")
    .lte("trial_end", new Date().toISOString())
    .select("id, business_id, plan_id");
  if (error) throw error;
  for (const sub of (data ?? []) as { id: string; business_id: string; plan_id: string }[]) {
    await auditBilling(sub.business_id, "billing.trial_ended", "subscription", sub.id, { plan_id: sub.plan_id });
    await reconcileSubscriptionLicenses(sub.id);
  }
  return data?.length ?? 0;
}

/** PLATFORM-P1-04.3 -- re-provisions every past_due subscription whose payment grace has
 * run out, so its licences start the read-only grace. Idempotent: reconciliation acts only
 * on the difference. */
export async function enforcePaymentGrace(): Promise<number> {
  const lifecycle = await loadLifecycleSettings();
  const cutoff = new Date(Date.now() - lifecycle.paymentGraceDays * 24 * 60 * 60 * 1000).toISOString();
  const { data, error } = await platformAdmin()
    .from("subscriptions")
    .select("id")
    .eq("status", "past_due")
    .lte("past_due_since", cutoff);
  if (error) throw error;
  let changed = 0;
  for (const sub of (data ?? []) as { id: string }[]) {
    const result = await reconcileSubscriptionLicenses(sub.id);
    if (result.deactivated.length > 0) changed++;
  }
  return changed;
}

/** Sweeps open sessions past their expiry (§52). Returns how many expired. */
export async function expireCheckoutSessions(): Promise<number> {
  const { data, error } = await platformAdmin()
    .from("checkout_sessions")
    .update({ status: "expired" })
    .eq("status", "open")
    .lt("expires_at", new Date().toISOString())
    .select("id");
  if (error) throw error;
  return data?.length ?? 0;
}
