import { after } from "next/server";
import { completeExportJob, queueExportJob } from "@cofounderai/core/exports/jobs";
import type { LargeExportHandler } from "@cofounderai/core/exports/server";

/**
 * EXP-PLAT-06 -- what the export route does with a dataset over the synchronous row limit:
 * record a job, answer `202 Export queued` straight away, and build the file after the
 * response has been sent. `after()` keeps the request's own context -- the user's session
 * cookies -- so the file is written, and the job updated, as that user, under RLS. The
 * bell then shows "Export ready" (lib/exports/alerts.ts) linking to the download.
 */
export const handleLargeExport: LargeExportHandler = async ({ context, adapterId, workbook, filters }) => {
  const job = await queueExportJob(context, adapterId, workbook.title, filters);
  if (job) {
    after(() =>
      completeExportJob(
        job.id,
        context,
        workbook,
        {
          Business: context.businessName,
          "Generated by": context.userEmail ?? context.userId,
          Rows: context.scope === "all" ? "All matching records" : "Current view",
        },
        filters,
      ),
    );
  }
  return Response.json(
    {
      status: "queued",
      message: job
        ? "Your export is being prepared. We'll notify you when it is ready."
        : "This export is already being prepared. We'll notify you when it is ready.",
    },
    { status: 202, headers: { "cache-control": "no-store" } },
  );
};
